pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    heroProfileImage:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 500
                                    height: 500
                                    positioning: center
                                    forceResize: false
                        medias: {  }
                        name: heroProfileImage
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1695704550
                        creationDate: 1695704294
                        preserveAnimation: false
