pimcore:
    general:
        domain: www.hempel.localhost
        redirect_to_maindomain: false
        language: en
        valid_languages:
            - en
            - de
        fallback_languages:
            en: ''
            de: ''
        default_language: en
        debug_admin_translations: false
    documents:
        versions:
            days: null
            steps: null
        error_pages:
            default: /error
            localized:
                en: ''
                de: ''
    objects:
        versions:
            days: null
            steps: null
    assets:
        versions:
            days: null
            steps: null
    email:
        debug:
            email_addresses: bjoern@hempel.li
