pimcore_static_routes:
    definitions:
        44b66fb9-c157-44b8-ae49-c3089a2d8874:
            name: blog
            pattern: /blog
            reverse: /blog
            controller: null
            variables: ''
            defaults: ''
            siteId: {  }
            methods: {  }
            priority: 0
            creationDate: 1694459483
            modificationDate: 1694563018
