pimcore_static_routes:
    definitions:
        7268d0d2-f448-4c60-8070-09ab4a5d1082:
            name: contact
            pattern: /contact
            reverse: /contact
            controller: null
            variables: ''
            defaults: ''
            siteId: {  }
            methods: {  }
            priority: 0
            creationDate: 1694953466
            modificationDate: 1694953478
